### ISSUE TITLE
Support variable interpolation

### ISSUE THREAD

**Issue by JanStevens** [Nebo15/ecto_mnesia#19]
Hello,

Variable interpolation in a where clause is not working.

```elixir
%Protocol.UndefinedError{description: "", protocol: Enumerable, value: {:^, [], [0]}}
  1) test where where `in` strings (Ecto.Mnesia.Context.MatchSpecTest)
     test/unit/match_spec_test.exs:162
     ** (Protocol.UndefinedError) protocol Enumerable not implemented for {:^, [], [0]}
     stacktrace:
       (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir) lib/enum.ex:116: Enumerable.reduce/3
       (elixir) lib/enum.ex:1636: Enum.reduce/3
       (elixir) lib/enum.ex:1188: Enum.map/2
       (ecto_mnesia) lib/ecto_mnesia/record/context/match_spec.ex:84: Ecto.Mnesia.Record.Context.MatchSpec.match_condition/3
       (ecto_mnesia) lib/ecto_mnesia/record/context/match_spec.ex:66: Ecto.Mnesia.Record.Context.MatchSpec.match_conditions/4
       (ecto_mnesia) lib/ecto_mnesia/record/context/match_spec.ex:22: Ecto.Mnesia.Record.Context.MatchSpec.update/2
       test/unit/match_spec_test.exs:21: Ecto.Mnesia.Context.MatchSpecTest.ms/1
       test/unit/match_spec_test.exs:166: (test)
```

The test I'm currently using

```elixir
test "where `in` strings" do
   variable = ["ok", "canceled"]
   query = from so in SellOffer, where: so.status in ^variable
   assert [{_, [{:or, {:==, @status_field_id, "ok"}, {:==, @status_field_id, "canceled"}}], _}] = ms(query)
end
```

I'm willing to contribute but a point in the good direction might help, currently I see a difference in the query param passed to `def update` in match_spec.

```
Ecto.Query<from s in SellOffer, where: s.status in ["ok", "canceled"]
```

vs

```
#Ecto.Query<from s in SellOffer, where: s.status in ^["ok", "canceled"]>
```

**Comment by JanStevens** [comment]
After some inspecting I found out the difference in a query with variable interpolation and without. On line 58 in `match_spec` I see that the where condition is different depending on the query. This causes the `match_condition({:in, [], ...)` call to fail.

```
With: Ecto.Query<from s in SellOffer, where: s.status in ["ok", "canceled"]>
[%Ecto.Query.BooleanExpr{expr: {:in, [],
   [{{:., [], [{:&, [], [0]}, :status]}, [], []}, ["ok", "banana"]]},
  file: "/Users/fritz/PP/ecto_mnesia/test/unit/repo_test.exs", line: 19,
  op: :and, params: nil}]
```

```
with: Ecto.Query<from s in SellOffer, where: s.status in ^["ok", "canceled"]>
[%Ecto.Query.BooleanExpr{expr: {:in, [],
   [{{:., [], [{:&, [], [0]}, :status]}, [], []}, {:^, [], [0, 2]}]},
  file: "/Users/fritz/PP/ecto_mnesia/test/unit/repo_test.exs", line: 20,
  op: :and, params: nil}]
```

The `match_condition` will assume in the second case that `{:^, [], [0, 2]}` is the parameters list when it in fact is something else. To me it seems odd that ecto doesn't take care of the interpolation, but ho well. My current fix is to swap them manually but this is just a poor mans implementation (read hack). I place it right before the `match_condition({:in, [], [field, parameters]...)`

```
  defp match_condition({:in, [], [field, {:^, [], _}]}, sources, context) do
    # Notice that I place the sources in the right place
    match_condition({:in, [], [field, sources]}, sources, context)
  end
```

**Comment by AndrewDryga** [comment]
This is a little bit more complex. We need a way to parse sources, since it will contain all possible interpolations, and we need to extract the right one from them.

**Comment by AndrewDryga** [comment]
I'll try to make this test pass:
```
    test "`in` with interpolation" do
      statuses = ["ok", "canceled"]
      loan_product_types = ["PDL"]

      query =
        from so in SellOffer,
        where: so.status in ^statuses or so.age in [21, 23] or so.loan_product_type in ^loan_product_types

      assert [{_, [{:or, {:==, @status_field_id, "ok"}, {:==, @status_field_id, "canceled"}}], _}] = ms(query)
    end
```
