### ISSUE TITLE
 Field `:id` does not exist in table

### ISSUE THREAD

**Issue by walkr** [Nebo15/ecto_mnesia#36]
I'm planning to use ecto_mnesia for a project as a message store, but I can't get it to work.

```elixir
 create_if_not_exists table(:messages, engine: :set) do
 # ...
```

```elixir
config :ecto_mnesia,
  host: Kernel.node(),
  storage_type: :ram_copies
```

```shell
iex(3)> MnesiaRepo.all(Message)
** (ArgumentError) Field `:id` does not exist in table `:messages`
    (ecto_mnesia) lib/ecto_mnesia/record/context.ex:91: EctoMnesia.Record.Context.find_field_placeholder!/2
         (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (ecto_mnesia) lib/ecto_mnesia/record/context/match_spec.ex:17: EctoMnesia.Record.Context.MatchSpec.update/2
    (ecto_mnesia) lib/ecto_mnesia/planner.ex:57: EctoMnesia.Planner.execute/6
           (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
           (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
``` 

Any thoughts?

Thank you!

**Comment by walkr** [comment]
Oops, it looks like the cause was an improperly defined migration.
Solved!
