### ISSUE TITLE
Failing to order by a non unique field

### ISSUE THREAD

**Issue by mathieul** [Nebo15/ecto_mnesia#38]
First of all thank you for sharing ecto_mnesia! Using Mnesia via Ecto sounds a bit like magic 👍.

I am running into a problem when ordering by a field with non unique values.

For instance:

```elixir
# Example schema
defmodule Activity.Example do
  use Ecto.Schema
  import Ecto.Query, only: [from: 2]

  schema "examples" do
    field :name, :string
  end

  def recent(scope \\ __MODULE__) do
    from(e in scope, order_by: [desc: :name])
  end
end
```

```elixir
# in iex
iex(3)> Ecto.Changeset.cast(%Activity.Example{}, %{name: "one"}, [:name]) |> Activity.Repo.insert()
{:ok,
 %Activity.Example{__meta__: #Ecto.Schema.Metadata<:loaded, "examples">, id: 1,
  name: "one"}}
iex(4)> Ecto.Changeset.cast(%Activity.Example{}, %{name: "two"}, [:name]) |> Activity.Repo.insert()
{:ok,
 %Activity.Example{__meta__: #Ecto.Schema.Metadata<:loaded, "examples">, id: 2,
  name: "two"}}
iex(5)> Ecto.Changeset.cast(%Activity.Example{}, %{name: "one"}, [:name]) |> Activity.Repo.insert()
{:ok,
 %Activity.Example{__meta__: #Ecto.Schema.Metadata<:loaded, "examples">, id: 3,
  name: "one"}}
iex(6)> Activity.Example.recent |> Activity.Repo.all
[debug] Selecting all records by match specification `[{{:examples, :"$1", :"$2"}, [], [[:"$1", :"$2"]]}]` with limit nil
** (FunctionClauseError) no function clause matching in EctoMnesia.Record.Ordering.cmp/3
    (ecto_mnesia) lib/ecto_mnesia/record/ordering.ex:30: EctoMnesia.Record.Ordering.cmp(%Activity.Example{__meta__: #Ecto.Schema.Metadata<:loaded, "examples">, id: 1, name: "one"}, %Activity.Example{__meta__: #Ecto.Schema.Metadata<:loaded, "examples">, id: 3, name: "one"}, [])
    (ecto_mnesia) lib/ecto_mnesia/record/ordering.ex:22: EctoMnesia.Record.Ordering.sort/3
         (stdlib) lists.erl:969: :lists.sort/2
    (ecto_mnesia) lib/ecto_mnesia/planner.ex:64: EctoMnesia.Planner.execute/6
           (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
           (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
```

Looking at `EctoMnesia.Record.Ordering.cmp` it seems that the case where left and right are still equal after applying all join expressions is not handled.

I've fixed the problem for me by appending a `defp cmp(_, _, []), do: :gt` function declaration to `EctoMnesia.Record.Ordering`. But being a rookie in Mnesia I could obviously be missing something.

**Comment by AndrewDryga** [comment]
Hello. Thanks for trying adapter 👍.

Thats definitely a bug, I will look into it. And I guess your fix is the correct one 👍
