### ISSUE TITLE
[error] Could not retrieve migrated versions.

### ISSUE THREAD

**Issue by rschooley** [Nebo15/ecto_mnesia#50]
First, thanks for this driver/lib, it's great to get mensia with ecto.

For this issue, sometimes I run my test suite and I get this error.  If I just keep rerunning my test suite it will eventually run without the error, not sure what the problem is.

```
[error] Could not retrieve migrated versions. This error usually happens due to the following:

  * The database does not exist
  * The "schema_migrations" table, which Ecto uses for managing
    migrations, was defined by another library

To fix the first issue, run "mix ecto.create".

To address the second, you can run "mix ecto.drop" followed by
"mix ecto.create". Alternatively you may configure Ecto to use
another table for managing migrations:

    config :foo, Foo.Repo,
      migration_source: "some_other_table_for_schema_migrations"

The full error report is shown below.

** (RuntimeError) Schema :schema_migrations does not exist
    lib/ecto_mnesia/table.ex:165: EctoMnesia.Table.transaction/2
    lib/ecto_mnesia/planner.ex:62: EctoMnesia.Planner.execute/6
    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
    (ecto) lib/ecto/migrator.ex:284: Ecto.Migrator.verbose_schema_migration/3
    (ecto) lib/ecto/migrator.ex:155: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:84: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by AndrewDryga** [comment]
Do you use default `mnesia_dir` or an overriden one?

**Comment by rschooley** [comment]
An overridden one to `/usr/local/var/`

**Comment by rschooley** [comment]
Any chance of getting a fix for this.  The driver is pretty much unusable with this issue.

**Comment by rschooley** [comment]
I switched to using the default dir and still get this issue.  If I rerun mix test enough times it will eventually work.

Is it some race condition when trying to load the database from disk?

**Comment by AndrewDryga** [comment]
@rschooley I plan to work on adapter compatibility with upcoming Ecto 3.0 and will try to address this issue there.

It's hard to tell what exactly is happening, if you can provide a repo that reproduces this issue, I'd be more than happy to investigate it deeper.

**Comment by rschooley** [comment]
Cool, thanks for the reply.

As a temporary fix I removed the create and migrate from the test aliases in mix.exs

```
"test": ["ecto.create --quiet", "ecto.migrate", "test"]
```
is now 
```
"test": ["test"]
```

in my project and I can continue.
